### PR TITLE
#161966900 Upgrade Authors Haven Django app from Django 1…

### PR DESCRIPTION
**Pull request by PromasterGuru**
#### What does this PR do?
Upgrade Authors Haven Django app from Django 1.10 to Django 2.1.3

#### Description of Task to be completed?
- Uninstall Django 1.10
- Install Django 2.1.3
- Change the Django version in the requirements.txt to Django 2.1.3

#### Any background context you want to provide?
Django 2.x is the latest release of Django with the full support of the Python 3.x series.

#### What are the relevant pivotal tracker stories?
[#162036573](https://www.pivotaltracker.com/story/show/161966900)

### CODE REVIEW

**Comment by r-wambui** [comment]
@PromasterGuru Change the description of the task to be completed.

**Comment by PromasterGuru** [comment]
@r-wambui I have made the changes I had promised regarding the `Description of task to be completed.`

**Comment by leonardnjura** [comment]
Good @PromasterGuru this PR will be so relevant with the contemporary Django.

**Comment by PromasterGuru** [comment]
> Good @PromasterGuru this PR will be so relevant with the contemporary Django.

Thank you @leonardnjura. Django 2.1.3 eliminates several bugs that were discovered in Django 1.1.0. One of them is a regression in Django 1.11 where django-admin shell used to hang on startup. That makes it the best choice for this project.

**Comment by ThaDeveloper** [comment]
@PromasterGuru Good PR, great upgrading to Django 2.x. Also, ensure the settings.py docstrings reflect the upgrade.

**Comment by amutava** [comment]
Thinking our loud on whether you should replace some files here with the ones generated by django 2...check on that in regard to urls.py and settings.py. i bet urls in django 1 are very much different from ones in django 2. cc @r-wambui .

**Comment by r-wambui** [comment]
@andela-amutava I had requested him to look at the files which change in django 2 as well. But probably some of these they can still do them as they handle the functionality. Since the requirements is already updated to django 2, as they develop the functionality, these changes will be inevitable. They can do this as they learn django. That's my take though.

**Comment by PromasterGuru** [comment]
> Thinking our loud on whether you should replace some files here with the ones generated by django 2...check on that in regard to urls.py and settings.py. i bet urls in django 1 are very much different from ones in django 2. cc @r-wambui .

@andela-amutava Great idea, we will work on that as we implement the tests.

**Pull request merged**
