### PR TITLE
#161966899 mockup login and registration  pages

### PR DESCRIPTION
**Pull request by kamyaD**
#### What does this PR do?

This PR has a   login and registration pages where users login and sign up respectively.

#### Description of Task to be completed?

Have an HTML mockup login and registration pages to demonstrate implementation of the Frontend.

#### How should this be manually tested?

* Run the `git clone https://github.com/andela/ah-infinity-stones.git` command in your terminal.
* cd into the `ah-infinity-stones` folder
* `git checkout` into the   branch
* Open the login.html template on your browser
* Enter user details then click submit to test.

#### Any background context you want to provide?

Users will need privacy hence the need to have registration and login to secure their account

#### What are the relevant pivotal tracker stories?

[#161966899](https://www.pivotaltracker.com/story/show/161966899)

#### Screenshots

screen shot 2018-11-29 at 18 26 36
screen shot 2018-11-29 at 18 26 11

### CODE REVIEW

**Comment by PromasterGuru** [comment]
@kamyaD nice job on the detailed PR. However could you update the relevant pivotal tracker story id to link the user to the PT story.

Thank you for the feedback, I have done as you suggested.

**Comment by kamyaD** [comment]
> @kamyaD nice job on the detailed PR. However could you update the relevant pivotal tracker story id to link the user to the PT story.

@PromasterGuru Thank you for the ASK feedback, Let me work on it right away.

**Comment by ThaDeveloper** [comment]
@kamyaD This looks can be merged.

**Comment by kamyaD** [comment]
> > @kamyaD nice job on the detailed PR. However could you update the relevant pivotal tracker story id to link the user to the PT story.
> 
> @PromasterGuru Thank you for the ASK feedback, Let me work on it right away.

@PromasterGuru The changes are complete. Thanks

**Pull request merged**
