### PR TITLE
#161966907 Integrate Coveralls code coverage service

### PR DESCRIPTION
**Pull request by PromasterGuru**
#### What does this PR do?
Integrate Coveralls code coverage service

#### Description of Task to be completed?
- Integrate the repository with coveralls.io
- Add coveralls badge to the README.md file

#### How should this be manually tested?
1. Visit https://github.com/andela/ah-infinity-stones/
2. Select ` ch-coveralls-code-coverage-161966907` branch.
3. Click the coverall badge. This will redirect you to the coveralls.io webpage with Andela/

#### What are the relevant pivotal tracker stories?
[#161966900](https://www.pivotaltracker.com/story/show/161966900)

### CODE REVIEW

**Comment by r-wambui** [comment]
@PromasterGuru _The Description of the task to be completed_  on the PR is misleading. Kindly change that.

**Comment by PromasterGuru** [comment]
@r-wambui Hey, I have updated my PR to make the description of the task to be completed more clear.

**Comment by r-wambui** [comment]
@PromasterGuru Kindly solve the merge conflicts above.

**Comment by PromasterGuru** [comment]
> @PromasterGuru Kindly solve the merge conflicts above.

@r-wambui Okay, am working on that. Thank you.

**Comment by PromasterGuru** [comment]
@r-wambui I have resolved the merge conflict.

**Pull request merged**
