### PR TITLE
#161966899 Create profile pages

### PR DESCRIPTION
**Pull request by rkemmy**
### What does this PR do?
Creates  a profile and edit profile pages.

### Description of Task to be Completed
Generate mockups to illustrate the profile and edit profile pages of the website.

### How should this be manually tested?
* Run the `git clone https://github.com/andela/ah-infinity-stones.git` command in your terminal.
* cd into the `ah-infinity-stones` folder
* `git checkout` into the ft-profile-page-#161966899  branch
* Open the profile.html template on your browser

### Relevant Pivotal Tracker Stories
[#161966899](https://www.pivotaltracker.com/story/show/161966899)

### Screenshots
screen shot 2018-11-29 at 23 43 18
screen shot 2018-11-29 at 23 44 28

### CODE REVIEW

**Comment by kamyaD** [comment]
Wow! this looks professional. I am happy you managed to finally get the right background combination.

**Comment by codeplus254** [comment]
Did you manage to set up the "My Stories" page?

**Comment by ThaDeveloper** [comment]
Looks nice, though the search button looks separate from the search input box which is different in the home navbar.Also, the PR should be done against `gh-pages`

**Comment by PromasterGuru** [comment]
@rkemmy Great work, kindly update the PR to have the relevant PT stories section appear before the Screenshots section.

**Comment by rkemmy** [comment]
Thanks, @PromasterGuru and @ThaDeveloper for the observation I have made the necessary changes. @codeplus254 the user stories were done by Leo.

**Pull request merged**
